### ISSUE TITLE
LAN-Erkennung nicht zuverlässig

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/node_hierarchy#4]
Moin,

wie bei Whatsapp besprochen, hier der Bericht zum Problem mit der LAN-Erkennung.

An etwa 3-4 Standorten hat das nicht funktioniert, ein Beispiel ist dieses hier: https://karte.freifunk-muensterland.de/map21/#!v:m;n:a42bb0d89cf6

Grüße
Matthias

**Comment by descilla** [comment]
Hallo,
das Problem ist, dass ich es anhand dieses Knotens nicht mehr nachvollziehen kann, da dieser nun in einer anderen Domäne ist und daher die meshviewer Topologie eine andere ist. Ich schaue, ob ich alte json files bekomme, wo der Knoten noch in der alten Domäne war. Ansonsten müssten wir einen anderen "Testkandidaten" finden, der sich noch in einer fastd Domäne befindet.

Grüße
descilla

**Comment by descilla** [comment]
Siehe commit message. Ich kann jedoch nicht ausschließen, dass es false positive LAN-Erkennungen gibt, daher bitte testen.
