### ISSUE TITLE
Offlineknoten eines Polygons ausgeben

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/node_hierarchy#5]
Moin,

wie gestern besprochen, brauchen wir einen Filter, der innerhalb eines Polygons (oder gleich mehrerer separat) die Offlineknoten ausgibt.

Die Ausgabe kann identisch zur normalen Verwendung sein, also IPV6 und Knotenname in einer Zeile, das passt dann schon.

Man sollte allerdings im Filter einstellen können, wie lange sie mindestens offline sind. Als Standardwert fände ich 120 Stunden (fünf Tage) gut.

@descilla 

Grüße
Matthias

**Comment by descilla** [comment]
Modul hinzugefügt, siehe README.md. Allerdings gibt es jetzt nur filter für Tage, Wochen und Monate. Sind Stunden relevant? Dann füge ich sie noch hinzu.

**Comment by MPW1412** [comment]
Ne, Tage sollten reichen. Danke!
